### PR TITLE
Fixed README

### PR DESCRIPTION
**Pull request by tusharpm**
Modified the comments for the hsl function return values.

### CODE REVIEW

**Comment by Qix-** [comment]
Hey thanks for the PR :) In the future, do `git pull --rebase origin master` so we don't get the `Merge remote-tracking branch 'MoOx/master'` commits ;)

I'll merge this in the morning :+1: Thank you again!

**Comment by tusharpm** [comment]
I'm still learning git. I'll do that from now on. Thanks.

**Comment by Qix-** [comment]
No problem :) I didn't know about `git pull --rebase` until a little bit ago, too.

**Comment by Qix-** [comment]
Sorry I'm just now getting to this.

In the future, try to put new things on their own branch as well ;)

**Comment by Qix-** [comment]
Thanks! Landed in 4565f55257b5b0a43828942014264c85f9f4ed42.

**Pull request closed without merging**
